//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDSRenameUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDSRenameUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A22E	WarioWare: Touched! (Demo) 
        ///A22P	WarioWare - Touched! (Demo)
        ///A23E	Super Mario 64 DS (Demo)
        ///A26E	Feel the Magic - XY-XX (Demo)
        ///A26P	Project Rub (Demo)
        ///A27P	Yoshi Touch &amp; Go (Demo)
        ///A29E	Pac-Pix (Demo)
        ///A29P	Pac-Pix (Demo)
        ///A2AJ	Atama no Kaiten no Training - Rubik&apos;s Cube &amp; Chou Yuumei Puzzle-tachi
        ///A2BJ	Super Black Bass - Dynamic Shot
        ///A2DC	New Chaoji Maliou Xiongdi
        ///A2DE	New Super Mario Bros.
        ///A2DJ	New Super Mario Bros.
        ///A2DK	New Super Mario Bros.
        ///A2DP	New Super Mario Bros.
        ///A2FJ	Tokimeki Memorial [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GamesTDB {
            get {
                return ResourceManager.GetString("GamesTDB", resourceCulture);
            }
        }
    }
}
